export const mockConsultations = [
  {
    id: '1',
    date: '2025-08-15',
    time: '14:00',
    doctor: 'Dr. João Silva',
    specialty: 'Cardiologia',
    location: 'Clínica Saúde Viva',
  },
  {
    id: '2',
    date: '2025-08-15',
    time: '09:30',
    doctor: 'Dra. Maria Souza',
    specialty: 'Dermatologia',
    location: 'Hospital Central',
  },
  {
    id: '3',
    date: '2025-08-12',
    time: '14:00',
    doctor: 'Dr. João Silva',
    specialty: 'Cardiologia',
    location: 'Clínica Saúde Viva',
  },
  {
    id: '4',
    date: '2025-08-15',
    time: '14:00',
    doctor: 'Dr. João Silva',
    specialty: 'Cardiologia',
    location: 'Clínica Saúde Viva',
  },
  {
    id: '5',
    date: '2025-08-15',
    time: '09:30',
    doctor: 'Dra. Maria Souza',
    specialty: 'Dermatologia',
    location: 'Hospital Central',
  },
  {
    id: '6',
    date: '2025-08-12',
    time: '14:00',
    doctor: 'Dr. João Silva',
    specialty: 'Cardiologia',
    location: 'Clínica Saúde Viva',
  }
];
